# Generated by Django 5.2 on 2025-04-16 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(),
        ),
    ]
