# Generated by Django 5.2 on 2025-09-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_company_expiry_date_company_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
    ]
