# Generated by Django 5.2 on 2025-04-16 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_job_alter_job_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='comment_company', to='inventory.company'),
            preserve_default=False,
        ),
    ]
