# Generated by Django 5.2 on 2025-07-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quote_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='quoted_declined',
            field=models.BooleanField(default=False),
        ),
    ]
