# Generated by Django 5.2 on 2025-09-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_customuser_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-changed_at']},
        ),
    ]
