# Generated by Django 5.2 on 2025-09-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_history_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='quoted_declined',
            new_name='quote_declined',
        ),
    ]
