# Generated by Django 5.1.6 on 2025-03-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_customuser_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
    ]
