# Generated by Django 5.2 on 2025-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_job_quote_accepted_job_quoted_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
