# Generated by Django 5.2 on 2025-09-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_quoted_declined_job_quote_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='added_by_batch_entry',
            field=models.BooleanField(default=False),
        ),
    ]
