# Generated by Django 5.1.6 on 2025-04-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_item_quantity_item_job_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='arrived_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
