# Generated by Django 5.2 on 2025-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
