# Generated by Django 5.2 on 2025-09-27 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_jobitem_added_by_batch_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_birthday',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
