# Generated by Django 5.1.6 on 2025-03-27 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_customuser_group_alter_customuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.ManyToManyField(related_name='workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
