# Generated by Django 5.2 on 2025-09-27 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_job_job_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_birthday',
        ),
        migrations.AddField(
            model_name='job',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
