# Generated by Django 5.1.6 on 2025-04-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_arrived_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
