# Generated by Django 5.2 on 2025-09-27 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_job_job_birthday_job_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
