# Generated by Django 5.1.6 on 2025-04-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.job'),
        ),
    ]
