# Generated by Django 5.1.6 on 2025-03-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_company_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='workers',
        ),
    ]
