# Generated by Django 5.1.6 on 2025-03-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_company_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='inventory.company'),
            preserve_default=False,
        ),
    ]
