# Generated by Django 5.2 on 2025-08-09 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('batch', 'Batch')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
