# Generated by Django 5.1.6 on 2025-04-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_notes_alter_item_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_moved_to_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
