# Generated by Django 5.1.6 on 2025-03-27 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.company'),
        ),
    ]
