# Generated by Django 5.1.6 on 2025-04-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_is_moved_to_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
