# Generated by Django 5.2 on 2025-08-10 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='company',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='company_history', to='inventory.company'),
            preserve_default=False,
        ),
    ]
