# Generated by Django 5.2 on 2025-08-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_history_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='company',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='jobitem_company', to='inventory.company'),
            preserve_default=False,
        ),
    ]
