# Generated by Django 5.2 on 2025-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_job_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='added_by_batch_entry',
            field=models.BooleanField(),
        ),
    ]
