# Generated by Django 5.1.6 on 2025-04-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_item_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='job',
        ),
        migrations.RemoveField(
            model_name='item',
            name='job_quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='reference',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_quantity', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_items', to='inventory.item')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.job')),
            ],
        ),
    ]
