# Generated by Django 5.2 on 2025-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_jobitem_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
