# Generated by Django 5.1.6 on 2025-04-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_item_job_remove_item_job_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='arrived_quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='required_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
