# Generated by Django 5.1.6 on 2025-03-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_item_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='needed_parts',
        ),
    ]
