# Generated by Django 5.1.6 on 2025-03-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_job_needed_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='needed_parts',
            field=models.ManyToManyField(blank=True, related_name='items', to='inventory.item'),
        ),
    ]
