# Generated by Django 5.1.6 on 2025-04-29 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_item_arrived_quantity_item_required_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_moved_to_warehouse',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_warehouse_item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='arrived_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('arrived', 'Arrived'), ('not_ordered', 'Not ordered')], default='not_ordered', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='inventory.job'),
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_quantity', models.PositiveSmallIntegerField(default=0)),
                ('arrived_quantity', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('arrived', 'Arrived'), ('not_ordered', 'Not ordered')], default='not_ordered', max_length=20)),
                ('is_moved_from_job', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_items', to='inventory.item')),
            ],
        ),
    ]
