# Generated by Django 5.2 on 2025-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_history_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobitem',
            name='notes',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='was_it_used',
            field=models.BooleanField(default=False),
        ),
    ]
