# Generated by Django 5.2 on 2025-10-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_jobitem_added_by_batch_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='need_attention',
            field=models.BooleanField(default=False),
        ),
    ]
