# Generated by Django 5.1.6 on 2025-04-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_item_is_moved_to_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='item',
            name='warehouse_quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='arrived_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('arrived', 'Arrived'), ('not_ordered', 'Not ordered')], default='not_ordered', max_length=20),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
