# Generated by Django 5.2 on 2025-10-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_job_need_attention'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='need_attention',
            new_name='on_hold',
        ),
    ]
