# Generated by Django 5.1.6 on 2025-03-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_job_needed_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='needed_parts',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='items_pics/yahia.jpg', upload_to='items_pics'),
        ),
    ]
