# Generated by Django 5.1.6 on 2025-03-29 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_job_needed_parts_alter_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='added_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='arrived_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='job',
        ),
        migrations.RemoveField(
            model_name='item',
            name='jobid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.IntegerField()),
                ('quantity_arrived', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('arrived', 'Arrived')], default='pending', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_items', to='inventory.item')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_items', to='inventory.job')),
            ],
        ),
    ]
