# Generated by Django 5.2 on 2025-10-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_rename_need_attention_job_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='retirement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
