# Generated by Django 5.1.6 on 2025-04-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_item_is_used_remove_item_warehouse_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitem',
            name='job_quantity',
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='warehouse_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
