# Generated by Django 5.2 on 2025-10-05 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_job_retirement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='retirement_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
