# Generated by Django 5.1.6 on 2025-03-29 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_item_options_remove_item_added_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='inventory.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='parent_account',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='quantity_arrived',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='quantity_needed',
            field=models.PositiveIntegerField(),
        ),
    ]
