# Generated by Django 5.1.6 on 2025-04-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_warehouseitem_job_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitem',
            name='arrived_quantity',
        ),
    ]
