# Generated by Django 5.2 on 2025-10-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_job_retirement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='retirement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
