# Generated by Django 5.1.6 on 2025-03-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_item_name_alter_job_address_alter_job_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='added_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='parent_account',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.TextField(max_length=70),
        ),
        migrations.DeleteModel(
            name='JobItem',
        ),
    ]
