# Generated by Django 5.2 on 2025-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_job_retirement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='sf_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
