# Generated by Django 5.1.6 on 2025-04-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_company_items', to='inventory.company'),
            preserve_default=False,
        ),
    ]
