# Generated by Django 5.1.6 on 2025-03-30 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_item_name_remove_job_added_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='dd', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='part_number',
            field=models.TextField(default=4, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.CharField(default='s', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='parent_account',
            field=models.TextField(default='DD', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('ready', 'Ready'), ('completed', 'Completed'), ('paused', 'Paused')], default='arrived', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
