# Generated by Django 5.2 on 2025-10-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_engineer_sf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='added_by_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
