# Generated by Django 5.1.6 on 2025-05-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_warehouseitem_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='from_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
