# Generated by Django 5.1.6 on 2025-03-30 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_job_id_item_arrived_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_company', to='inventory.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job', to='inventory.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='inventory.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('paused', 'Paused'), ('completed', 'Completed'), ('ready', 'Ready'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
