# Generated by Django 5.2 on 2025-10-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_job_added_by_sync_job_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created_by_syncing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='updated_by_syncing',
            field=models.BooleanField(default=False),
        ),
    ]
