# Generated by Django 5.1.6 on 2025-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_item_company_item_job_job_company_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('paused', 'Paused'), ('ready', 'Ready'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20),
        ),
    ]
