# Generated by Django 5.1.6 on 2025-03-31 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='inventory.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('paused', 'Paused'), ('ready', 'Ready'), ('completed', 'Completed')], max_length=20),
        ),
    ]
