# Generated by Django 5.2 on 2025-10-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_history_created_by_syncing_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='engineer',
            unique_together={('email', 'company')},
        ),
    ]
