# Generated by Django 5.2 on 2025-10-14 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_engineer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_ids', models.TextField()),
                ('map_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_groups', to='inventory.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scheduler_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
