# Generated by Django 5.1.6 on 2025-03-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_item_job_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='parent_account',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
