# Generated by Django 5.1.6 on 2025-03-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_job_parent_account_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='items_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='needed_items',
            field=models.ManyToManyField(related_name='job_items', to='inventory.item'),
        ),
    ]
