# Generated by Django 5.2 on 2025-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_schedulergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulergroup',
            name='optimized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
