# Generated by Django 5.2 on 2025-10-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_schedulergroup_optimized_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulergroup',
            name='job_ids',
        ),
        migrations.AddField(
            model_name='schedulergroup',
            name='jobs',
            field=models.ManyToManyField(related_name='job_groups', to='inventory.job'),
        ),
    ]
