# Generated by Django 5.2 on 2025-05-12 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_engineer_company_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineers_company', to='inventory.company'),
        ),
    ]
