# Generated by Django 5.2 on 2025-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_schedulergroup_job_ids_schedulergroup_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulergroup',
            name='wrong_postcodes',
            field=models.BooleanField(default=False),
        ),
    ]
