# Generated by Django 5.2 on 2025-10-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_schedulergroup_wrong_postcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulergroup',
            name='job_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
