# Generated by Django 5.2 on 2025-05-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_engineer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitem',
            name='status',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='was_for_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moveditems', to='inventory.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.engineer'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='is_moved_from_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehousemoveditems', to='inventory.job'),
        ),
    ]
