# Generated by Django 5.1.6 on 2025-04-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_remove_customuser_group_alter_customuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
