# Generated by Django 5.2 on 2025-11-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_schedulergroup_job_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='db_host',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='db_pass',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='db_user',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='use_own_db',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='integrate_sf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_client_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_client_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='inventory.company'),
        ),
    ]
