# Generated by Django 5.2 on 2025-05-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_remove_warehouseitem_status_jobitem_was_for_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitem',
            name='is_used',
        ),
    ]
