# Generated by Django 5.2 on 2025-11-11 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_companysettings_db_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parts_need_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_scheduler_distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_scheduler_group_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
