# Generated by Django 5.1.6 on 2025-04-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_company_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name'], 'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='job',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
