# Generated by Django 5.2 on 2025-05-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_warehouseitem_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
