# Generated by Django 5.2 on 2025-11-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_job_parts_need_attention_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='integrate_sf',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='sf_access_token',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='sf_client_id',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='sf_client_secret',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='sf_refresh_token',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='sf_token_expires',
        ),
    ]
