# Generated by Django 5.2 on 2025-11-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_remove_companysettings_integrate_sf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='integrate_sf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_client_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_client_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='sf_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
