# Generated by Django 5.2 on 2025-05-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_jobitem_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='status',
            field=models.CharField(blank=True, choices=[('arrived', 'Arrived'), (' ', '')], default=None, max_length=20, null=True),
        ),
    ]
