# Generated by Django 5.1.6 on 2025-04-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_item_added_by_alter_item_job_alter_item_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
