# Generated by Django 5.2 on 2025-05-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_jobitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quotation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
