# Generated by Django 5.2 on 2025-11-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_companysettings_integrate_sf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='inventory.company'),
        ),
    ]
