# Generated by Django 5.2 on 2025-06-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_job_quotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-added_date']},
        ),
        migrations.AddField(
            model_name='item',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
