# Generated by Django 5.2 on 2025-11-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_companysettings_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sf_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
