# Generated by Django 5.2 on 2025-06-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_job_options_item_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reference',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='reference',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='reference',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
