# Generated by Django 5.2 on 2025-11-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_job_sf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sf_id',
            field=models.PositiveIntegerField(blank=True, max_length=40, null=True),
        ),
    ]
