# Generated by Django 5.1.6 on 2025-04-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_item_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
