# Generated by Django 5.2 on 2025-11-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_job_sf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sf_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
