# Generated by Django 5.2 on 2025-06-06 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_item_reference_jobitem_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobitem_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouseitem_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
