# Generated by Django 5.1.6 on 2025-04-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_item_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='arrived',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('arrived', 'Arrived'), ('quoted', 'Quoted'), ('empty', '')], default='empty', max_length=20),
        ),
    ]
