# Generated by Django 5.1.6 on 2025-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_remove_item_arrived_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='part_number',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('arrived', 'Arrived'), ('not_ordered', 'Not ordered')], default='not_ordered', max_length=20),
        ),
    ]
