# Generated by Django 5.2 on 2025-06-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_jobitem_added_by_jobitem_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reference',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
