# Generated by Django 5.2 on 2025-11-22 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_job_sf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 22, 14, 51, 7, 866463, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
