# Generated by Django 5.1.6 on 2025-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_item_part_number_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('quoted', 'Quoted and waiting')], max_length=20),
        ),
    ]
