# Generated by Django 5.2 on 2025-06-06 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_item_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouseitem_moved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='moved_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='added_date',
            field=models.DateTimeField(),
        ),
    ]
