# Generated by Django 5.2 on 2025-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_jobitem_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='ordered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
