# Generated by Django 5.1.6 on 2025-04-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_job_quoted_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
