# Generated by Django 5.2 on 2025-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_jobitem_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='arrived_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
