# Generated by Django 5.2 on 2025-06-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_warehouseitem_moved_by_warehouseitem_moved_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobitem',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='jobitem',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='moved_by',
        ),
        migrations.RemoveField(
            model_name='warehouseitem',
            name='moved_date',
        ),
    ]
