# Generated by Django 5.1.6 on 2025-04-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_job_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='comments',
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_comments', to='inventory.job')),
            ],
        ),
    ]
