# Generated by Django 5.2 on 2025-11-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_jobitem_arrived_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('GBP', 'GBP (£)')], default='GBP', max_length=10),
        ),
    ]
