# Generated by Django 5.2 on 2025-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_remove_jobitem_added_by_remove_jobitem_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_Employee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_owner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
