# Generated by Django 5.2 on 2025-11-26 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_companysettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='from_sf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('GBP', '£')], default='GBP', max_length=10),
        ),
    ]
