# Generated by Django 5.2 on 2025-06-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_remove_customuser_is_employee_customuser_permission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['is_owner', 'is_admin', 'is_employee', 'is_banned'], 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='permission',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('owner', 'Owner')], default='employee'),
        ),
    ]
