# Generated by Django 5.1.6 on 2025-04-16 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_comment_options_comment_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_by',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
