# Generated by Django 5.2 on 2025-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_customuser_options_alter_company_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='notes',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
