# Generated by Django 5.2 on 2025-06-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_remove_item_notes_jobitem_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobitem',
            name='status',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
    ]
