# Generated by Django 5.2 on 2025-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_job_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulergroup',
            name='scheduler',
            field=models.BooleanField(default=False),
        ),
    ]
