# Generated by Django 5.2 on 2025-12-08 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_schedulergroup_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulergroup',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.engineer'),
        ),
    ]
