# Generated by Django 5.2 on 2025-12-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_schedulergroup_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulergroup',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
