# Generated by Django 5.2 on 2025-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_schedulergroup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='imported_from_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='imported_from_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
