# Generated by Django 5.2 on 2025-12-14 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_comment_imported_from_sheet_job_imported_from_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.job'),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='was_for_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moveditems', to='inventory.job'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='is_moved_from_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehousemoveditems', to='inventory.job'),
        ),
    ]
