# Generated by Django 5.2 on 2026-01-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_alter_email_user_alter_history_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='preferred_scheduler_distance',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='preferred_scheduler_group_size',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='group_size',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
