# Generated by Django 5.2 on 2026-01-06 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_usersettings_user_alter_usersettings_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='group_size',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
