# Generated by Django 5.2 on 2026-01-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_alter_job_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
