# Generated by Django 5.2 on 2026-01-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_alter_job_address_alter_job_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='calendar_engineer_filter',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='calendar_parts_filter',
            field=models.CharField(default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='calendar_status_filter',
            field=models.CharField(default='all', max_length=20),
        ),
    ]
