# Generated by Django 5.2 on 2026-04-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='who_has_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.engineer'),
        ),
    ]
