# Generated by Django 5.2 on 2026-04-29 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_alter_jobitem_who_has_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='who_has_part',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.engineer'),
        ),
    ]
