# Generated by Django 5.2 on 2026-05-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_warehouseitem_who_has_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='sf_id',
        ),
    ]
