# Generated by Django 5.2 on 2026-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_remove_engineer_sf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='sf_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='synced_from_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
